# Generated by Django 2.2.3 on 2019-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snacks',
            name='snack_description',
            field=models.CharField(default='desc', max_length=200),
        ),
    ]
