# Generated by Django 2.2.3 on 2019-07-23 14:17

from django.db import migrations, models
import django.db.models.deletion
import snacktracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0002_snacks_snack_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='requests',
            name='operation',
            field=models.CharField(default='view', max_length=200),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Snacks', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Snacks', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=snacktracker.models.get_image_path)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Snacks', unique=True)),
            ],
        ),
    ]
