# Generated by Django 2.2.3 on 2019-07-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0003_auto_20190723_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='operation',
        ),
    ]
