# Generated by Django 2.2.3 on 2019-07-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0004_remove_requests_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Snacks'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Snacks'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Snacks'),
        ),
    ]
