# Generated by Django 2.2.3 on 2019-07-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0006_auto_20190723_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='Operations',
            new_name='Operation',
        ),
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
        migrations.RenameModel(
            old_name='Snacks',
            new_name='Snack',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
