# Generated by Django 2.2.3 on 2019-07-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0007_auto_20190723_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=200)),
                ('password', models.CharField(default='admin', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='dislikes',
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.IntegerField(default=0)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Snack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snacktracker.User')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snacktracker.User'),
        ),
    ]
