# Generated by Django 2.2.3 on 2019-07-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0008_auto_20190724_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snacktracker.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='admin@admin.com', max_length=200),
        ),
    ]
