# Generated by Django 2.2.3 on 2019-07-24 22:31

from django.db import migrations, models
import django.db.models.deletion
import snacktracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0009_auto_20190724_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.CharField(default='yummy', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=snacktracker.models.get_image_path),
        ),
        migrations.AddField(
            model_name='request',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Tag'),
        ),
        migrations.AddField(
            model_name='snack',
            name='snack_image',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='snack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snacktracker.Snack'),
        ),
    ]
