# Generated by Django 2.2.3 on 2019-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacktracker', '0012_auto_20190724_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='snack_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
